name = "qwintly-gateway-worker"
main = "index.ts"
compatibility_date = "2024-04-03"

[vars]
ALLOWED_TARGET_HOST_SUFFIX = ".run.app"
URL_LOOKUP_CACHE_TTL_MS = "10800000"

[env.prod]
name = "qwintly-gateway-worker"

[env.dev]
name = "qwintly-gateway-worker-dev"
